# config/packages/easy_admin.yaml
easy_admin:
  entities:
      Articles:
        class: App\Entity\Articles
        list:
          fields:
            - "nom"
            - "description"
            - "prix"
            - "categorie"
            - { property: 'image', type: 'image', base_path: '/images/articles' }

        show:
          fields:
            - { property: 'image', type: 'image', base_path: '/images/articles' }
        form:
          fields:
            - "nom"
            - "description"
            - "prix"
            - "categorie"
            - { property: 'imageFile', type: 'vich_image' }

#      Commandes:
#        class: App\Entity\Commande
#        list:
#          fields:
#            - "client->getUsername()"
#            - "total"
#            - "date"
    # change the following to the namespaces of your own entities


#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
