vich_uploader:
    db_driver: orm
    mappings:
         articles_images:
            uri_prefix:         /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
